import { VerticalBox, HorizontalBox, ScrollView, ComboBox, LineEdit, Button } from "std-widgets.slint";
import { FragranceCard } from "../components/fragrance_card.slint";
import { FragranceData, FragranceRow } from "../types.slint";

export component CollectionPage inherits Rectangle {
    in-out property <string> sort-option: "Rating: High → Low";
    in-out property <string> search-text: "";
    in property <image> fragrance-image;
    in property <[FragranceRow]> rows;

    callback fragrance_clicked(FragranceData);
    callback search_requested(string);
    callback sort_requested(string);
    background: #181818;

    VerticalBox {
        padding: 30px;
        spacing: 20px;

        HorizontalBox {
            spacing: 20px;

            Text {
                text: "Collection";
                font-size: 40px;
                color: white;
                vertical-alignment: center;
            }

            LineEdit {
                width: 220px;
                placeholder-text: "Search fragrances...";
                text <=> root.search-text;

                edited => {
                    root.search_requested(self.text);
                }
            }

            Button {
                width: 70px;
                text: "Clear";

                clicked => {
                    root.search-text = "";
                    root.search_requested("");
                }
            }

            ComboBox {
                width: 160px;

                model: [
                    "Rating: High → Low",
                    "Rating: Low → High",
                    "Name: A → Z",
                    "Name: Z → A"
                ];

                current-value <=> root.sort-option;

                selected => {
                    root.sort_requested(root.sort-option);
                }
            }
        }

        ScrollView {
            vertical-stretch: 1;

            VerticalBox {
                spacing: 20px;

                for row in root.rows : HorizontalBox {
                    spacing: 20px;

                    for fragrance in row.fragrances : FragranceCard {
                        brand: fragrance.brand;
                        name: fragrance.name;
                        rating: fragrance.rating;
                        notes: fragrance.notes;
                        seasons: fragrance.seasons;
                        fragrance-image: fragrance.image;

                        card_clicked => {
                            root.fragrance_clicked(fragrance);
                        }
                    }
                }
            }
        }
    }
}