import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { FragranceCard } from "../components/fragrance_card.slint";
import { FragranceData, FragranceRow } from "../types.slint";

export component CollectionPage inherits Rectangle {
    in property <[FragranceRow]> rows;
    background: #181818;

    VerticalBox {

        padding: 30px;
        spacing: 20px;

        Text {
            text: "Collection";
            font-size: 32px;
            color: white;
        }

        ScrollView {
            vertical-stretch: 1;

            VerticalBox {
                spacing: 20px;

                for row in root.rows : HorizontalBox {
                    spacing: 20px;

                    for fragrance in row.fragrances : FragranceCard {
                        brand: fragrance.brand;
                        name: fragrance.name;
                        rating: fragrance.rating;
                        notes: fragrance.notes;
                        seasons: fragrance.seasons;
                    }
                }
            }
        }
    }
}