import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export component FragranceCard inherits Rectangle {

    width: 220px;
    height: 320px;

    background: #242424;
    border-radius: 12px;


    VerticalBox {

        padding: 15px;
        spacing: 10px;


        Rectangle {

            height: 150px;

            background: #333333;

            Text {
                text: "Bottle";
                color: #aaaaaa;
                horizontal-alignment: center;
            }
        }


        Text {
            text: "Bleu de Chanel";
            color: white;
            font-size: 18px;
        }


        Text {
            text: "⭐ 9.2";
            color: white;
        }


        Text {
            text: "Grapefruit • Cedar • Incense";
            color: #aaaaaa;
        }


        Text {
            text: "☀ Summer  🍂 Fall";
            color: #aaaaaa;
        }
    }
}