import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";

export component sidebar inherits Rectangle{
    callback add_requested();
    callback dashboard_requested();
    callback collection_requested();
    callback settings_requested();

    width: 280px;
    background: #1e1e1e;

    VerticalBox {
        padding: 20px;
        spacing: 15px;

        Text {
            text: "Fragrance Vault";
            font-size: 35px;
            color: white;
            wrap: word-wrap;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        Rectangle {
            height: 20px;
        }

        Button {
            text: "🏠 Dashboard";
            clicked => {
                root.dashboard_requested();
            }
        }

        Button {
            text: "📚 Collection";
            clicked => {
                root.collection_requested();
            }
        }

        Button {
            text: "⭐ Rankings";
        }

        Button {
            text: "❤️ Wishlist";
        }

        Button {
            text: "➕ Add Fragrance";
            clicked => {
                root.add_requested();
            }
        }

        Button {
            text: "⚙ Settings";
            clicked => {
                root.settings_requested();
            }
        }
    }
}