import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";

export component sidebar inherits Rectangle{
    width: 280px;
    background: #1e1e1e;

    VerticalBox {
        padding: 20px;
        spacing: 15px;

        Text {
            text: "Fragrance Vault";
            font-size: 35px;
            color: white;
            wrap: word-wrap;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        Rectangle {
            height: 20px;
        }

        Button {
            text: "🏠 Dashboard";
        }

        Button {
            text: "📚 Collection";
        }

        Button {
            text: "⭐ Rankings";
        }

        Button {
            text: "❤️ Wishlist";
        }

        Button {
            text: "➕ Add Fragrance";
        }

        Button {
            text: "⚙ Settings";
        }
    }
}