pub struct Fragrance {
    pub id: i64,
    pub brand: String,
    pub name: String,
    pub concentration: String,
    pub projection: String,
    pub longevity: String,
    pub price: String,
    pub purchase_date: String,
    pub notes: String,
    pub seasons: String,
    pub image_path: String,
    pub my_notes: String,
    pub partner_notes: String,
    pub image_offset_x: f64,
    pub image_offset_y: f64,
    pub image_scale: f64,
    pub category: String,
}

pub struct NewFragrance<'a> {
    pub brand: &'a str,
    pub name: &'a str,
    pub concentration: &'a str,
    pub projection: &'a str,
    pub longevity: &'a str,
    pub price: &'a str,
    pub purchase_date: &'a str,
    pub notes: &'a str,
    pub seasons: &'a str,
    pub image_path: &'a str,
    pub my_notes: &'a str,
    pub partner_notes: &'a str,
    pub image_offset_x: f64,
    pub image_offset_y: f64,
    pub image_scale: f64,
    pub category: &'a str,
}

pub struct UpdateFragrance<'a> {
    pub id: i64,
    pub brand: &'a str,
    pub name: &'a str,
    pub concentration: &'a str,
    pub projection: &'a str,
    pub longevity: &'a str,
    pub price: &'a str,
    pub purchase_date: &'a str,
    pub notes: &'a str,
    pub seasons: &'a str,
    pub my_notes: &'a str,
    pub partner_notes: &'a str,
    pub image_path: &'a str,
    pub image_offset_x: f64,
    pub image_offset_y: f64,
    pub image_scale: f64,
    pub category: &'a str,
}