import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { sidebar } from "./components/sidebar.slint";
import { CollectionPage } from "./pages/collection.slint";
import { FragranceDetails } from "./pages/fragrance_details.slint";
import { EditFragrance } from "./pages/edit_fragrance.slint";
import { Page, FragranceRow, FragranceData } from "./types.slint";

export component MainWindow inherits Window {
    callback save_requested(
        string,
        string,
        float,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
    );
    width: 1200px;
    height: 800px;

    in-out property <Page> current-page: Page.Collection;
    in property <[FragranceRow]> rows;
    property <FragranceData> selected-fragrance;
    
    title: "Fragrance Vault";

    background: #121212;

    HorizontalBox {
        sidebar{}

        // Main Content Area
        Rectangle {
            horizontal-stretch: 1;
            if root.current-page == Page.Collection : CollectionPage {
                rows: root.rows;
                fragrance_clicked(fragrance) => {
                    root.selected-fragrance = fragrance;
                    root.current-page = Page.Details;
                }
            }

            if root.current-page == Page.Details : FragranceDetails {
                fragrance: root.selected-fragrance;

                edit_requested => {
                    root.current-page = Page.Edit;
                }

                delete_requested => {
                    // next step: confirmation dialog
                }

                back_requested => {
                    root.current-page = Page.Collection;
                }
            }

            if root.current-page == Page.Edit : EditFragrance {
                fragrance: root.selected-fragrance;
                cancel_requested => {
                    root.current-page = Page.Details;
                }

                save_requested(
                    brand,
                    name,
                    rating,
                    concentration,
                    projection,
                    longevity,
                    price,
                    purchase_date,
                    notes,
                    seasons,
                    my_notes,
                    partner_notes
                ) => {
                    root.selected-fragrance = {
                        id: root.selected-fragrance.id,
                        brand: brand,
                        name: name,
                        concentration: concentration,
                        projection: projection,
                        longevity: longevity,
                        price: price,
                        purchase_date: purchase_date,
                        rating: rating,
                        notes: notes,
                        seasons: seasons,
                        image_path: root.selected-fragrance.image_path,
                        my_notes: my_notes,
                        partner_notes: partner_notes
                    };

                    root.save_requested(
                        brand,
                        name,
                        rating,
                        concentration,
                        projection,
                        longevity,
                        price,
                        purchase_date,
                        notes,
                        seasons,
                        my_notes,
                        partner_notes
                    );

                    root.current-page = Page.Details;
                }
            }
        }
    }
}