export struct FragranceData {
    id: int,
    brand: string,
    name: string,
    concentration: string,
    projection: string,
    longevity: string,
    price: string,
    purchase_date: string,
    rating: float,
    notes: string,
    seasons: string,
    image: image,
    my_notes: string,
    partner_notes: string,
    image_path: string,
    image_offset_x: float,
    image_offset_y: float,
    image_scale: float,
    season_spring: bool,
    season_summer: bool,
    season_fall: bool,
    season_winter: bool,
    category: string,
}

export struct FragranceInput {
    id: int,
    brand: string,
    name: string,
    rating: float,
    concentration: string,
    projection: string,
    longevity: string,
    price: string,
    purchase_date: string,
    notes: string,
    season_spring: bool,
    season_summer: bool,
    season_fall: bool,
    season_winter: bool,
    category: string,
    my_notes: string,
    partner_notes: string,
    image_path: string,
    image_offset_x: float,
    image_offset_y: float,
    image_scale: float,
}

export struct ImageSelection {
    path: string,
    picture: image,
}

export struct FragranceRow {
    fragrances: [FragranceData],
}

export struct DashboardData {
    total: int,
    average_rating: float,
    highest_rated: FragranceData,
    lowest_rated: FragranceData,
    most_common_season: string,
    season_top: [FragranceData],
    recently_added: [FragranceData],
    top_cologne: [FragranceData],
    top_perfume: [FragranceData],
}

export enum Page {
    Collection,
    Details,
    Edit,
    Add,
    Dashboard,
}