export struct FragranceData {
    id: int,
    brand: string,
    name: string,
    concentration: string,
    projection: string,
    longevity: string,
    price: string,
    purchase_date: string,
    rating: float,
    notes: string,
    seasons: string,
    image: image,
    my_notes: string,
    partner_notes: string,
}

export struct FragranceRow {
    fragrances: [FragranceData],
}

export enum Page {
    Collection,
    Details,
    Edit, 
    Add
}